version: '3'
services:

  apache:
    container_name: apache # TODO: once for each project e.g: `apache-project_name`
    restart: always
    build: .docker/apache
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM
    ports:
      - 8181:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/app:cached # TODO: Rebuild container after changes into root fs
    depends_on:
      - php

  db:
    container_name: db # TODO: once for each project e.g: `db-project_name`
    restart: always
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3339:3306
    volumes:
      - /opt/mysql_data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  php:
    container_name: php # TODO: once for each project e.g: `php-project_name`
    restart: always
    build: .docker/php
    ports:
      - 9990:9001
    volumes:
      - .:/var/www/app:cached
      - ./logs:/var/www/app/var/log:cached
    depends_on:
      - db # TODO: equal db container_name e.g: `db-project_name`
    extra_hosts:
      - docker-host.localhost:127.0.0.1
    ### change 127.0.0.1 to your local ip address